# Generated by Django 6.0.6 on 2026-08-13 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_datetime',
        ),
        migrations.RemoveField(
            model_name='table',
            name='capacity',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[(1, '07:00'), (2, '08:00'), (3, '09:00'), (4, '10:00'), (5, '11:00'), (6, '12:00'), (7, '13:00'), (8, '14:00'), (9, '15:00'), (10, '16:00'), (11, '17:00'), (12, '18:00'), (13, '19:00'), (14, '20:00'), (15, '21:00'), (16, '22:00')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
